### ISSUE TITLE
runnning sls-mentor gives error 'Cannot find module constants/runtimes'

### ISSUE THREAD

**Issue by cyberworkz** [sls-mentor/sls-mentor#142]
Error: Cannot find module 'constants/runtimes'
Require stack:
- /Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/rules/noDeprecatedRuntime/index.js
- /Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/rules/index.js
- /Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/checks.js
- /Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/slsMentor.js
- /Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/haiko/IdeaProjects/examples/online-library-cloudwatch-emf/node_modules/sls-mentor/dist/rules/noDeprecatedRuntime/index.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',

**Comment by PChol22** [comment]
Indeed, sorry for the inconvenience, I just released a fix in v2.1.8!

**Comment by cyberworkz** [comment]
Thanks for the fix. I can confirm it running now. Now I am encountering AWS access rights issues, but that is something else.
