### ISSUE TITLE
Cannot read properties of undefined (reading 'aws:SecureTransport')

### ISSUE THREAD

**Issue by mnapoli** [sls-mentor/sls-mentor#203]
Hello 👋

I'm facing an error that seems code-related, not sure! The command I ran was `npx sls-mentor@latest -p xxx -r sa-east-1` It installed the latest version (first time I used it in a while).

I should have admin access to the AWS account.

CLI output:

```
Welcome to sls-mentor 🛡️.

Let's start by selecting the level of difficulty you want me to check your code against.


⠇ Processing rules 17/30.../Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:1654
    ({ Effect, Condition }) => Effect === "Deny" && Condition.Bool["aws:SecureTransport"] === "false"
                                                                  ^

TypeError: Cannot read properties of undefined (reading 'aws:SecureTransport')
    at /Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:1654:67
    at Array.some (<anonymous>)
    at hasSSLConfiguration (/Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:1653:27)
    at /Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:1661:14
    at Array.map (<anonymous>)
    at /Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:1659:42
    at Generator.next (<anonymous>)
    at fulfilled (/Users/matthieu/.npm/_npx/dbb48ce8d1b45f02/node_modules/sls-mentor/dist/index.js:48:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.2.0
```

Does that ring a bell?

**Comment by PChol22** [comment]
Will be fixed in next release, thanks @JamesKyburz and @mnapoli !
